/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_watergate_library_LockEnv */

#ifndef _Callbacks_com_watergate_library_LockEnv
#define _Callbacks_com_watergate_library_LockEnv

#endif //_Callbacks_com_watergate_library_LockEnv
