/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_watergate_library_LockControlClient */

#ifndef _Callbacks_com_watergate_library_LockControlClient
#define _Callbacks_com_watergate_library_LockControlClient

#endif //_Callbacks_com_watergate_library_LockControlClient
