/* 
 * Copyright [2016] [Subhabrata Ghosh] 
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at 
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 *       limitations under the License. 
 * 
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_watergate_library_LockControlClient */


#ifndef _Callbacks_com_watergate_library_LockControlClient
#define _Callbacks_com_watergate_library_LockControlClient

#endif //_Callbacks_com_watergate_library_LockControlClient
