/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_watergate_library_LockControlManager */

#ifndef _Included_com_watergate_library_LockControlManager
#define _Included_com_watergate_library_LockControlManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_watergate_library_LockControlManager
 * Method:    create
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_watergate_library_LockControlManager_create
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_watergate_library_LockControlManager
 * Method:    clearLocks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_watergate_library_LockControlManager_clearLocks
  (JNIEnv *, jobject);

/*
 * Class:     com_watergate_library_LockControlManager
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_watergate_library_LockControlManager_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
