/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_watergate_library_LockControlManager */

#ifndef _Callbacks_com_watergate_library_LockControlManager
#define _Callbacks_com_watergate_library_LockControlManager

#endif //_Callbacks_com_watergate_library_LockControlManager
