/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_watergate_library_LockEnv */

#ifndef _Included_com_watergate_library_LockEnv
#define _Included_com_watergate_library_LockEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_watergate_library_LockEnv
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_watergate_library_LockEnv_create
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_watergate_library_LockEnv
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_watergate_library_LockEnv_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
